export const siteConfig = {
  name: "CHANGAO MA",
  siteUrl: "https://cv.maximoraverse.org",
  links: {
    github: "https://github.com/Maximora-byte",
    blog: "https://blog.maximoraverse.org",
    platform: "https://www.maximoraverse.org",
    contact: "https://auth.maximoraverse.org/contact",
  },
  skills: [
    "Python",
    "TypeScript",
    "Astro",
    "Linux",
    "Docker",
    "systemd",
    "GitHub Actions",
    "Caddy",
    "OAuth / OIDC",
    "Observability",
  ],
  projects: [
    {
      id: "swu-checkin",
      kind: "open-source",
      title: "SWU Check-in",
      eyebrow: "Python · Automation · Security",
      href: "https://github.com/Maximora-byte/swu-checkin",
      featured: true,
    },
    {
      id: "matchall",
      kind: "platform",
      title: "MatchAll Platform",
      eyebrow: "Cloud · Identity · Operations",
      href: "https://www.maximoraverse.org",
      featured: true,
    },
    {
      id: "swu-busmini",
      kind: "open-source",
      title: "SWU Busmini",
      eyebrow: "TypeScript · Mini Program · Navigation",
      href: "https://github.com/Maximora-byte/swu-busmini",
      featured: false,
    },
    {
      id: "icpc-lab",
      kind: "lab",
      title: "ICPC Lab",
      eyebrow: "C++ · Algorithms · Practice",
      href: "https://github.com/Maximora-byte/icpctest",
      featured: false,
    },
  ],
};
